apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-awx-single-postgres-0-pv
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  hostPath:
    path: /tmp/awx-postgres-data