kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: nm-rabbitmq
spec:
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: web
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: cluster
      protocol: TCP
      port: 25672
      targetPort: 25672
  selector:
    app: rabbitmq
  type: NodePort
