apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfs-jenkins-home
  namespace: nm-jenkins
spec:
  accessModes:
    - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: gfs-jenkins-home
