apiVersion: v1
kind: Service
metadata:
  name: graylog-input-tcp
  namespace: nm-graylog
spec:
  ports:
  - name: gelf-tcp
    port: 12201
    protocol: TCP
    targetPort: 12201
  - name: syslog-tcp
    port: 1514
    protocol: TCP
    targetPort: 1514
  selector:
    app: graylog
  type: ClusterIP
