apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: nm-graylog
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: graylog
  type: LoadBalancer
