kind: Deployment
apiVersion: apps/v1
metadata:
  name: graylog
  namespace: nm-graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      volumes:
        - name: graylog-conf
          configMap:
            name: graylog-config
            items:
              - key: server.conf
                path: graylog.conf
      containers:
        - name: graylog
          image: 'graylog/graylog:4.0'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: gelf-tcp
              containerPort: 12201
              protocol: TCP
            - name: gelf-udp
              containerPort: 12201
              protocol: UDP
            - name: syslog-tcp
              containerPort: 1514
              protocol: TCP
            - name: syslog-udp
              containerPort: 1514
              protocol: UDP
          env:
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: 'http://10.10.67.211/'
            - name: GRAYLOG_ROOT_TIMEZONE
              value: America/Bahia
          volumeMounts:
            - name: graylog-conf
              mountPath: /usr/share/graylog/data/config/graylog.conf
              subPath: graylog.conf
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
