apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nm-nexus
  labels:
    app: repository
spec:
  selector:
    app: repository
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  - name: docker-proxy
    port: 3000
    protocol: TCP
    targetPort: 8082
  - name: docker-private
    port: 3001
    protocol: TCP
    targetPort: 8083
  type: LoadBalancer
