kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus
  namespace: nm-nexus
  labels:
    app: repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repository
  template:
    metadata:
      labels:
        app: repository
    spec:
      volumes:
        - name: vol-nexus-data
          persistentVolumeClaim:
            claimName: gfs-nexus-data
        - name: config-files
          configMap:
            name: nexus-config-files
            items:
              - key: elasticsearch.yml
                path: conf-elasticsearch
              - key: nexus.vmoptions
                path: conf-vmoptions
              - key: karaf-system.properties
                path: conf-properties
      containers:
        - name: nexus
          image: 'sonatype/nexus3:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: docker-proxy
              containerPort: 8082
              protocol: TCP
            - name: docker-private
              containerPort: 8083
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: vol-nexus-data
              mountPath: /nexus-data
            - name: config-files
              mountPath: /opt/sonatype/nexus/etc/fabric/elasticsearch.yml
              subPath: conf-elasticsearch
            - name: config-files
              mountPath: /opt/sonatype/nexus/bin/nexus.vmoptions
              subPath: conf-vmoptions
            - name: config-files
              mountPath: /opt/sonatype/nexus/etc/karaf/system.properties
              subPath: conf-properties
          readinessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  strategy:
    type: Recreate
