- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  apt: 
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Install Docker APT key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

#- name: Install Docker APT key (method #2)
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 7EA0A9C3F273FCD8
#    state: present

- name: Adds Docker repository
  #apt_repository:
  #  repo: deb https://download.docker.com/linux/ubuntu bionic stable
  #  state: present
  shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null 
    creates: /etc/apt/sources.list.d/docker.list 

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes
   
- name: Ensure that Docker service is up and running
  service:
    name: docker
    state: started
    enabled: yes

