---
--- Cluster ElasticSearch - Client nodes - Mínimo 1, ideal 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-client
  namespace: nm-elasticsearch
  labels:
    role: client
    version: '7.9.3'
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: client
      version: '7.9.3'
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: elasticsearch
        role: client
        version: '7.9.3'
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elastic-ingest-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          runAsUser: 1000
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        resources: {}
        ports:
        - containerPort: 9200
          name: es-http
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: elastic-ingest-config
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml