---
--- Cluster ElasticSearch - Configuração dos nós de ingestão (client)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-ingest-config
  namespace: nm-elasticsearch
  labels:
    component: elasticsearch
    role: client
data:
  ES_JAVA_OPTS: '-Xms512m -Xmx512m -Xlog:disable'
  elasticsearch.yml: |
    #bootstrap.memory_lock: true
    cluster.name: "es-cluster"
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 2
    discovery.seed_hosts: ["elasticsearch-discovery"]
    node.roles: [ingest]
    xpack.ml.enabled: false