---
--- Cluster ElasticSearch - Data nodes - Configurado p/ 4, escalável a partir de 1
--- - Trocar sc-nfs-test pela sua StorageClass de provisionamento dinâmico
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-data
  namespace: nm-elasticsearch
  labels:
    role: data
    version: '7.9.3'
spec:
  serviceName: nm-elasticsearch-data
  replicas: 4
  selector:
    matchLabels:
      component: elasticsearch
      role: data
      version: '7.9.3'
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
        version: '7.9.3'
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elastic-data-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          runAsUser: 1000
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        resources: {}
        ports:
        - containerPort: 9300
          name: es-transport
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: elastic-data-config
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      storageClassName: sc-nfs-test
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi