apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: nm-elasticsearch
  labels:
    component: elasticsearch
    role: master
    version: '7.9.3'
spec:
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
  selector:
    component: elasticsearch
    role: master
    version: '7.9.3'