#apiVersion: v1
#kind: Namespace
#metadata:
#  name: nm-cerebro
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-cerebro
  #namespace: nm-cerebro
  labels:
    app: es-cerebro
spec:
  selector:
    matchLabels:
      app: es-cerebro
  template:
    metadata:
      labels:
        app: es-cerebro
    spec:
      containers:
      - name: elasticsearch-cerebro
        image: lmenezes/cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cerebro
  #namespace: nm-cerebro
  labels:
    app: es-cerebro
spec:
  type: NodePort
  selector:
    app: es-cerebro
  ports:
  - port: 9000
    targetPort: 9000
