apiVersion: v1
kind: ConfigMap
metadata:
  name: config-es-master
data:
  elasticsearch.yml: |
    node.name: elasticsearch-master
    cluster.name: elastic-cluster
    cluster.initial_master_nodes: ["elasticsearch-master"]
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    xpack.security.enabled: false
    xpack.security.audit.enabled: false
    xpack.monitoring.enabled: false
    xpack.ml.enabled: false
    node.ml: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
  labels:
    service: elasticsearch-master
spec:
  type: ClusterIP
  selector:
    service: elasticsearch-master
  ports:
  - name: loadbalancer 
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: elastic-cluster-loadbalancer
#  labels:
#    service: elasticsearch-master
#spec:
#  type: NodePort
#  selector:
#    service: elasticsearch-master
#  ports:
#  - name: loadbalancer 
#    port: 9200
#    targetPort: 9200
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: elastic-cluster-transport
#  labels:
#    service: elasticsearch-master
#spec:
#  type: ClusterIP
#  selector:
#    service: elasticsearch-master
#  ports:
#  - name: transport
#    port: 9300
#    targetPort: 9300
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-cluster-master
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch-master
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: elasticsearch-master
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch-master
        resources:
            requests:
                memory: 1Gi
        securityContext:
          privileged: true
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: config-es-master
              key: ES_JAVA_OPTS
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: config-es-master
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
