apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-yaml
data:
  kibana.yml: |
    server:
      name: kibana
      host: "0"
    elasticsearch.hosts: [ "http://elasticsearch-cluster:9200" ]
    xpack:
      monitoring.ui.container.elasticsearch.enabled: true
      spaces.enabled: true
    logging:
      timezone: "America/Sao_Paulo"
      rotate:
        enabled: true
        everyBytes: 10485760
        keepFiles: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.9.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /api/status
            port: 5601
          initialDelaySeconds: 30
        volumeMounts:
        - name: config
          subPath: kibana.yml
          mountPath: /usr/share/kibana/config/kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    service: kibana
spec:
  type: LoadBalancer
  selector:
    run: kibana
  ports:
  - port: 80
    targetPort: 5601
