apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmenezes-cerebro
  labels:
    app: lmenezes-cerebro
spec:
  selector:
    matchLabels:
      app: lmenezes-cerebro
  template:
    metadata:
      labels:
        app: lmenezes-cerebro
    spec:
      containers:
      - name: lmenezes-cerebro
        image: lmenezes/cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 384Mi
          limits:
            cpu: 1000m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: lmenezes-cerebro
  labels:
    app: lmenezes-cerebro
spec:
  type: LoadBalancer
  selector:
    app: lmenezes-cerebro
  ports:
  - port: 80
    targetPort: 9000
