all:
  hosts:
  children:
    aws_vms:
      hosts:
        34.235.170.81:
      vars:
        remote_user: admin
        extra_device: /dev/xvdb
    vagrant_vms:
      hosts:
        192.168.56.105:
      vars:
        remote_user: vagrant
        extra_device: /dev/sdb
