apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfs-shared-claim
  namespace: rook-nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: gfs-shared-dynamic
  volumeMode: Filesystem
