- name: Install GNU Parted and LVM2 packages
  apt:
    pkg:
      - parted
      - lvm2
    state: latest
    update_cache: yes

- name: Create a new LVM primary partition
  parted:
    device: "{{ extra_device }}"
    label: gpt
    part_type: primary
    number: 1
    state: present

- name: Create a volume group on top of {{ extra_device }}p1
  lvg:
    vg: docker-vg
    pvs: "{{ extra_device }}p1"

- name: Create a logical volume on top of docker-vg
  lvol:
    vg: docker-vg
    lv: docker
    size: 100%FREE
    shrink: no

- name: Create a ext4 filesystem on LV debian
  community.general.filesystem:
    fstype: ext4
    dev: /dev/docker-vg/docker

- name: Stops Docker service
  service:
    name: docker
    state: stopped
    enabled: yes

- name: Mounts LV docker to /var/lib/docker
  mount:
    src: /dev/docker-vg/docker
    path: /var/lib/docker
    state: mounted
    fstype: ext4

- name: Starts Docker service
  service:
    name: docker
    state: started
    enabled: yes

