apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: nm-jenkins
  labels:
    app: pipeline
spec:
  selector:
    app: pipeline
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: agent
    port: 50000
    protocol: TCP
    targetPort: 50000
  type: LoadBalancer
