apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gfs-nexus-data
  namespace: nm-nexus
spec:
  accessModes:
    - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: gfs-nexus-data
