apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mikrotik-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.88.240-192.168.88.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-pools
  namespace: metallb-system
spec:
  ipAddressPools:
  - mikrotik-pool
