---
- name: Setup WebODM
  hosts: vagrantmachines 
  remote_user: vagrant
  become: yes
  become_method: sudo

  roles:
    - docker
  
  tasks:
    - name: Give group permission to vagrant user
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Test Docker
      shell: docker run hello-world
      
