ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.provider "virtualbox" do |v|
        v.name = "local-odm"
        v.memory = 1024
        v.cpus = 8
    end

    if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = true
    end

    config.vm.network "private_network", ip:"192.168.56.102", name: "VirtualBox Host-Only Ethernet Adapter"

    config.vm.provision "shell", inline: "echo hello", run: "always"

    #config.vm.provision "ansible", run: "always" do |ansible|
    #    ansible.playbook = "playbook.yml"
    #end
end

